/* INSERT BOOK RECORD */
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Yahari Ore no Seishun Love Come wa Machigatte Iru", "Wataru Watari", "Yahari Ore no Seishun Rabukome wa Machigatte Iru is a romantic comedy which revolves around antisocial high school student, Hachiman Hikigaya, who has no friends, no girlfriend, and a severely distorted view on life. When he sees his classmates talking excitedly about living their adolescent lives, he mutters, \“They're a bunch of liars.\” When he is asked about his future dreams, he responds, \“Not working.\” In an attempt to fix Hachiman's twisted personality, his teacher forces him to join the volunteer 'service club', where the only other member happens to be one of the school's most beautiful and smartest girls, Yukino Yukinoshita.", "/asset/book_img/oregairu.png");
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Zero No Tsukaima", "Yamaguchi Noboru", "At the Tristain Magic Academy, her classmates call bumbling witch-in-training Louise Francoise le Blanc de la Valliere \“Louise the Zero.\” During an important coming-of-age ritual, when each student must summon their own witch's familiar, Louise confirms her classmates' opinion by accidentally conjuring up a normal teenage boy from Japan. Whether the two of them like it or not, the laws of magic bind them as master and servant forever! A hilarious novel with romance intertwined.", "/asset/book_img/zero_no_tsukaima.png");
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Baka to Test to Shoukanjuu", "Inoue Kenji", "The protagonist is a guy who is among the stupidest of the stupidest in the school. In this school, your grades can, under the supervision of teachers, take a virtual form to do combat! However, if you leave an examination half way, you get zero marks. A bright and cute girl, Mizuki Himeji, was having a high fever during the examination. Despite her potential to be the second highest scorer in the level, she obtained zero marks for having left due to her illness and is thus allocated to the worst class, class F.", "/asset/book_img/baka_to_test.jpg");
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Re:Zero Kara Hajimeru Isekai Seikatsu", "Nagatsuki Tappei", "Suddenly a high school student Subaru Natsuki has been summoned to another world on the way back from the convenience store. With the biggest crisis of his life being summoned to another world and no sign of the one who summoned him things become worse when he is attacked. But when he is saved by a mysterious silver-haired girl with a fairy cat, Subaru cooperates with the girl to return the favor. When they finally manage to get a clue Subaru and the girl are attacked and killed by someone. Subaru then awakens in the place he was summoned and notices the ability he gained \“Returns by Death\” a helpless boy that only has the ability to rewind time by dying. And beyond the despair can he save the girl from the fate of death!", "/asset/book_img/re_zero.png");
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Ore no Imouto ga Konna ni Kawaii Wake ga Nai", "Fushimi Tsukasa", "Kyosuke Kosaka, a normal seventeen-year-old high-school student, hasn't gotten along with his younger sister, Kirino, in years. For longer than he can remember, Kirino has ignored his comings and goings and looked at him with spurning eyes. It seemed as if the relationship between Kyosuke and his sister, now fourteen, would continue this way forever. One day, however, Kyosuke finds a DVD case of a magical girl anime entitled Hoshikuzu Witch Meruru (Stardust Witch Meruru), which had fallen into the entranceway of his house. To Kyosuke's surprise, inside the case is a hidden adult video game titled Imoto to Koishiyo! (Love with Little Sister!)", "/asset/book_img/oreimo.png");
INSERT INTO book(BookName, Author, Synopsis, PicturePath) VALUES ("Toradora!", "Takemiya Yuyuko","Toradora!'s story begins with the male protagonist Ryuji Takasu who is frustrated at trying to look his best as he enters his second year of high school. Despite his gentle personality, his eyes make him look like an intimidating delinquent so he is utterly hopeless about his chances of getting a girlfriend anytime soon, and does not have many close friends either. After being greeted by his hungover mother in the morning, Ryuji goes to school and is happy to find that he gets to be in the same class as his best friend Yusaku Kitamura and crush Minori Kushieda. However, it is then that he unexpectedly knocks into \“the school's most dangerous animal of the highest risk level\” — Taiga Aisaka — who just happens to also be in his class, and is a good friend of Minori. Taiga has a negative attitude towards others and will not hesitate to snap at people. After meeting Ryuji, she takes an instant dislike of him. Taiga comes from a rich family, though she moved out to live on her own due to family issues, and by coincidence is now living in an apartment next door to Ryuji. After Ryuji discovers that Taiga has a crush on Yusaku, and Taiga finds out about Ryuji's affections towards Minori, Ryuji suggests that they cooperate so they can win the object of their affections. Ryuji says he will do anything to get closer to Minori, which Taiga exploits, making Ryuji her personal servant, and getting him to do household chores like cooking and cleaning for her. Taiga spends a lot of her time over at his house, so much so that she could almost be considered a member of his family. Since Ryuji spends a lot of time with Taiga, he is opened up to her world and to a side of her that most people do not see. The two also attempt to help each other in order to improve how people view them. Unknown to them, however, people they know from school start to become curious about their strange relationship together and rumors begin to spread about them.", "/asset/book_img/toradora.jpg");

/* Create Table for Access token */
DROP TABLE IF EXISTS AccessToken;
CREATE TABLE AccessToken
(
  TokenID VARCHAR(10) NOT NULL,
  ExpiryTime DATETIME NOT NULL,
  Browser TEXT NOT NULL,
  IpAddress TEXT NOT NULL,
  UserID INT NOT NULL,
  PRIMARY KEY (TokenID),
  FOREIGN KEY (UserID) REFERENCES User(UserID)
);