SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS User;
CREATE TABLE BookPrice
(
  BookID VARCHAR(255) NOT NULL,
  Price FLOAT(11,1) NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE BookCategory



SET FOREIGN_KEY_CHECKS = 1;