
CREATE DATABASE WsBook;

DROP TABLE IF EXISTS Prices;
CREATE TABLE Prices
(
  BookId VARCHAR(255) NOT NULL,
  Price FLOAT(11,1) NOT NULL,
  PRIMARY KEY(BookId),
  UNIQUE(BookId)
);

DROP TABLE IF EXISTS Orders;
CREATE TABLE Orders
(
	OrderId INT NOT NULL AUTO_INCREMENT,
	BookId VARCHAR(255) NOT NULL,
	UserId INT NOT NULL,
	Category VARCHAR(255) NOT NULL,
	Amount INT NOT NULL,
	OrderTime DATETIME NOT NULL,
	Score FLOAT,
	Comment TEXT,
	PRIMARY KEY(OrderId)
);
